In [15]:
import sqlite3
import pandas as pd

print("Libraries Loaded Successfully")

Libraries Loaded Successfully

In [16]:
conn = sqlite3.connect("../data/Superstore.db")

print("Database Created Successfully")

Database Created Successfully

In [17]:
df = pd.read_csv("../data/Superstore_Cleaned.csv")

df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [18]:
df.to_sql(
    "superstore",
    conn,
    if_exists="replace",
    index=False
)

print("Table Imported Successfully")

Table Imported Successfully

In [19]:
pd.read_sql(
    "SELECT * FROM superstore LIMIT 5",
    conn
)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [20]:
query = """
SELECT Category,
       SUM(Sales) AS TotalSales
FROM superstore
GROUP BY Category
"""

result = pd.read_sql(query, conn)

result

          Category   TotalSales
0        Furniture  741999.7953
1  Office Supplies  719047.0320
2       Technology  836154.0330

In [22]:
print(df.columns)

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [23]:
query = """
SELECT
    "Product Name",
    SUM(Sales) AS TotalSales
FROM superstore
GROUP BY "Product Name"
ORDER BY TotalSales DESC
LIMIT 5;
"""

pd.read_sql(query, conn)

                                        Product Name  TotalSales
0              Canon imageCLASS 2200 Advanced Copier   61599.824
1  Fellowes PB500 Electric Punch Plastic Comb Bin...   27453.384
2  Cisco TelePresence System EX90 Videoconferenci...   22638.480
3       HON 5400 Series Task Chairs for Big and Tall   21870.576
4         GBC DocuBind TL300 Electric Binding System   19823.479

In [26]:
query = """
SELECT
    strftime('%Y-%m', "Order Date") AS Month,
    SUM(Sales) AS TotalSales
FROM superstore
GROUP BY Month
ORDER BY Month;
"""

pd.read_sql(query, conn)

      Month   TotalSales
0   2014-01   14236.8950
1   2014-02    4519.8920
2   2014-03   55691.0090
3   2014-04   28295.3450
4   2014-05   23648.2870
5   2014-06   34595.1276
6   2014-07   33946.3930
7   2014-08   27909.4685
8   2014-09   81777.3508
9   2014-10   31453.3930
10  2014-11   78628.7167
11  2014-12   69545.6205
12  2015-01   18174.0756
13  2015-02   11951.4110
14  2015-03   38726.2520
15  2015-04   34195.2085
16  2015-05   30131.6865
17  2015-06   24797.2920
18  2015-07   28765.3250
19  2015-08   36898.3322
20  2015-09   64595.9180
21  2015-10   31404.9235
22  2015-11   75972.5635
23  2015-12   74919.5212
24  2016-01   18542.4910
25  2016-02   22978.8150
26  2016-03   51715.8750
27  2016-04   38750.0390
28  2016-05   56987.7280
29  2016-06   40344.5340
30  2016-07   39261.9630
31  2016-08   31115.3743
32  2016-09   73410.0249
33  2016-10   59687.7450
34  2016-11   79411.9658
35  2016-12   96999.0430
36  2017-01   43971.3740
37  2017-02   20301.1334
38  2017-03   58872.3528
39  2017-04   36521.5361
40  2017-05   44261.1102
41  2017-06   52981.7257
42  2017-07   45264.4160
43  2017-08   63120.8880
44  2017-09   87866.6520
45  2017-10   77776.9232
46  2017-11  118447.8250
47  2017-12   83829.3188

In [27]:
# Import required libraries
import sqlite3
import pandas as pd

# Connect to SQLite database
conn = sqlite3.connect("../data/Superstore.db")
print("Database Connected Successfully!")

# Load the cleaned dataset
df = pd.read_csv("../data/Superstore_Cleaned.csv")

# Rename all columns
df.columns = [
    "Row_ID",
    "Order_ID",
    "Order_Date",
    "Ship_Date",
    "Ship_Mode",
    "Customer_ID",
    "Customer_Name",
    "Segment",
    "Country",
    "City",
    "State",
    "Postal_Code",
    "Region",
    "Product_ID",
    "Category",
    "Sub_Category",
    "Product_Name",
    "Sales",
    "Quantity",
    "Discount",
    "Profit"
]

# Convert date columns
df["Order_Date"] = pd.to_datetime(df["Order_Date"])
df["Ship_Date"] = pd.to_datetime(df["Ship_Date"])

# Save data into SQLite
df.to_sql(
    "superstore",
    conn,
    if_exists="replace",
    index=False
)

print("Data Imported Successfully!")

# Display first 5 rows
print(df.head())

# Close connection
conn.close()

print("Database Connection Closed Successfully!")

Database Connected Successfully!
Data Imported Successfully!
   Row_ID        Order_ID Order_Date  Ship_Date       Ship_Mode Customer_ID  \
0       1  CA-2016-152156 2016-11-08 2016-11-11    Second Class    CG-12520
1       2  CA-2016-152156 2016-11-08 2016-11-11    Second Class    CG-12520
2       3  CA-2016-138688 2016-06-12 2016-06-16    Second Class    DV-13045
3       4  US-2015-108966 2015-10-11 2015-10-18  Standard Class    SO-20335
4       5  US-2015-108966 2015-10-11 2015-10-18  Standard Class    SO-20335

     Customer_Name    Segment        Country             City  ...  \
0      Claire Gute   Consumer  United States        Henderson  ...
1      Claire Gute   Consumer  United States        Henderson  ...
2  Darrin Van Huff  Corporate  United States      Los Angeles  ...
3   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...
4   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...

  Postal_Code  Region       Product_ID         Category Sub_Category  \
0       42420   South  FUR-BO-10001798        Furniture    Bookcases
1       42420   South  FUR-CH-10000454        Furniture       Chairs
2       90036    West  OFF-LA-10000240  Office Supplies       Labels
3       33311   South  FUR-TA-10000577        Furniture       Tables
4       33311   South  OFF-ST-10000760  Office Supplies      Storage

                                        Product_Name     Sales  Quantity  \
0                  Bush Somerset Collection Bookcase  261.9600         2
1  Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400         3
2  Self-Adhesive Address Labels for Typewriters b...   14.6200         2
3      Bretford CR4500 Series Slim Rectangular Table  957.5775         5
4                     Eldon Fold 'N Roll Cart System   22.3680         2

   Discount    Profit
0      0.00   41.9136
1      0.00  219.5820
2      0.00    6.8714
3      0.45 -383.0310
4      0.20    2.5164

[5 rows x 21 columns]
Database Connection Closed Successfully!

In [28]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("../data/Superstore.db")

pd.read_sql("PRAGMA table_info(superstore);", conn)

    cid           name       type  notnull dflt_value  pk
0     0         Row_ID    INTEGER        0       None   0
1     1       Order_ID       TEXT        0       None   0
2     2     Order_Date  TIMESTAMP        0       None   0
3     3      Ship_Date  TIMESTAMP        0       None   0
4     4      Ship_Mode       TEXT        0       None   0
5     5    Customer_ID       TEXT        0       None   0
6     6  Customer_Name       TEXT        0       None   0
7     7        Segment       TEXT        0       None   0
8     8        Country       TEXT        0       None   0
9     9           City       TEXT        0       None   0
10   10          State       TEXT        0       None   0
11   11    Postal_Code    INTEGER        0       None   0
12   12         Region       TEXT        0       None   0
13   13     Product_ID       TEXT        0       None   0
14   14       Category       TEXT        0       None   0
15   15   Sub_Category       TEXT        0       None   0
16   16   Product_Name       TEXT        0       None   0
17   17          Sales       REAL        0       None   0
18   18       Quantity    INTEGER        0       None   0
19   19       Discount       REAL        0       None   0
20   20         Profit       REAL        0       None   0

In [29]:
import pandas as pd

df = pd.read_csv("../data/Superstore.csv")

print(df.head())

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 2944: invalid start byte

In [30]:
import pandas as pd

df = pd.read_csv("../data/Superstore.csv", encoding="latin1")

df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [32]:
df = pd.read_csv("../data/Superstore.csv", encoding="latin1")

In [33]:
# Rename columns
df.columns = [
    "Row_ID",
    "Order_ID",
    "Order_Date",
    "Ship_Date",
    "Ship_Mode",
    "Customer_ID",
    "Customer_Name",
    "Segment",
    "Country",
    "City",
    "State",
    "Postal_Code",
    "Region",
    "Product_ID",
    "Category",
    "Sub_Category",
    "Product_Name",
    "Sales",
    "Quantity",
    "Discount",
    "Profit"
]

print(df.columns)

Index(['Row_ID', 'Order_ID', 'Order_Date', 'Ship_Date', 'Ship_Mode',
       'Customer_ID', 'Customer_Name', 'Segment', 'Country', 'City', 'State',
       'Postal_Code', 'Region', 'Product_ID', 'Category', 'Sub_Category',
       'Product_Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [36]:
df["Order_Date"] = pd.to_datetime(df["Order_Date"])
df["Ship_Date"] = pd.to_datetime(df["Ship_Date"])

In [37]:
import sqlite3

conn = sqlite3.connect("../data/Superstore.db")

df.to_sql(
    "superstore",
    conn,
    if_exists="replace",
    index=False
)

print("Data Imported Successfully!")

Data Imported Successfully!

In [38]:
pd.read_sql("SELECT * FROM superstore LIMIT 5;", conn)

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Country,City,...,Postal_Code,Region,Product_ID,Category,Sub_Category,Product_Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08 00:00:00,2016-11-11 00:00:00,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08 00:00:00,2016-11-11 00:00:00,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12 00:00:00,2016-06-16 00:00:00,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11 00:00:00,2015-10-18 00:00:00,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11 00:00:00,2015-10-18 00:00:00,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [39]:
query = """
SELECT
    Category,
    SUM(Sales) AS TotalSales
FROM superstore
GROUP BY Category;
"""

pd.read_sql(query, conn)

          Category   TotalSales
0        Furniture  741999.7953
1  Office Supplies  719047.0320
2       Technology  836154.0330

In [40]:
conn = sqlite3.connect("../data/Superstore.db")

In [41]:
import sqlite3

print(sqlite3.sqlite_version)

3.51.0